server:
  port: 8081
spring:
  application:
    name: spring-security-login-demo
  redis:
    host: 192.168.1.1
    database: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.1/yourDB?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-evictable-idle-time-millis: 60000
      keep-alive: true
      initial-size: 5
      min-idle: 1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义配置
validate:
  code:
    image:
      enabled: true  # 启用图片验证码校验功能